controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\News;
use app\models\NewsSearch;
use app\models\ConsultationOffice;
use app\models\ConsultationPhone;
use app\models\SignupForm;
use yii\web\BadRequestHttpException;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $modelOffice = new ConsultationOffice;
        $modelPhone = new ConsultationPhone;
        
        if($modelOffice->load(Yii::$app->request->post()) && $modelOffice->save()) {
            Yii::$app->session->setFlash('success', 'Ваша заявка сохранена.');
            return $this->refresh();
        }
        if($modelPhone->load(Yii::$app->request->post()) && $modelPhone->save()) {
            Yii::$app->session->setFlash('success', 'Ваша заявка сохранена.');
            return $this->refresh();
        }
        return $this->render('index', [
            'modelOffice' => $modelOffice,
            'modelPhone' => $modelPhone,
        ]);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['admin/site/index']);
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    
    public function actionRegistration()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if($user->activeAfterRegistration) {
                    if (Yii::$app->user->login($user))
                        return $this->goHome();
                } else {
                    Yii::$app->session->setFlash('success', 'Инструкции по завершению регистрации отправлены на Ваш e-mail.');
                    return $this->goHome();
                }
            }
        }
        
        return $this->render('registration', [
            'model' => $model
        ]);
    }
    
    public function actionAccauntActivation($token)
    {
        if (empty($token) || !is_string($token)) {
            throw new BadRequestHttpException('Токен не может быть пустым.');
        } else {
            $model = User::findOne(['auth_key' => $token]);
        }
        if (!$model || !$model->validateAuthKey($token)) {
            throw new BadRequestHttpException('Неправильный токен.');
        } elseif ($model->is_active > 0) {
            throw new BadRequestHttpException('Ваш аккаунт уже активирован.');
        } else {
            $model->is_active = 1;
            if($model->save()) {
                Yii::$app->session->setFlash('success', 'Ваш аккаунт активирован.');
                return $this->goHome();
            }
        }
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post())) {
            
            $admin = User::findOne(['status' => User::ROLE_ADMIN]);
            if (empty($admin) || empty($admin->email)) {
                throw new BadRequestHttpException('Не задан E-mail администратора.');
            } 
            $model->contact($admin->email);
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionNews()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('news', [
            'dataProvider' => $dataProvider
        ]);
    }
    
    public function actionArticle($slug)
    {
        $model = News::find()->where(['slug' => $slug])->asArray()->one();
        
        $this->isModel($model);
        
        return $this->render('article', [
            'model' => $model
        ]);
    }
    
    private function isModel($model)
    {
        if (!$model) {
            throw new BadRequestHttpException('Страница не найдена.');
        } 
    }
}

views/site/_news_item.php
<?php
use app\components\SiteHelper;
use yii\helpers\StringHelper;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $model \app\models\News */
?>

<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img src="<?=SiteHelper::resized_image($model->image, 340, 200)?>" alt="<?=$model->title?>" />
        <div class="caption">
            <h3><?=$model->title?></h3>
            <p><?=StringHelper::truncateWords(strip_tags($model->text), 15)?></p>
            <p><?=Html::a('Подробнее', ['/site/article', 'slug' => $model->slug], ['class' => 'btn btn-primary'])?></p>
        </div>
    </div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О нас';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

views/site/article.php
<?php
use app\components\SiteHelper;

/* @var $this yii\web\View */
/* @var $model \app\models\News */

$this->title = $model['title'];
$this->registerMetaTag(['name' => 'keywords', 'content' => $model['seo_key']]);
$this->registerMetaTag(['name' => 'description', 'content' => $model['seo_description']]);

?>

<div class="row">
    <div class="col-sm-6 col-md-4">
        <img width="100%" src="<?=SiteHelper::resized_image($model['image'], 340, 200)?>" alt="<?=$model['title']?>" />
    </div>
    <div class="col-sm-6 col-md-8">
        <h1><?=$model['title']?></h1>
        <span class="label label-info"><?=Yii::$app->formatter->asDate($model['created_at'], 'php:d F Y')?></span>
        <hr />
        <?=$model['text']?>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Контакты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Спасибо, что написали нам. Мы ответим Вам как можно скорее.
        </div>

    <?php else: ?>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        Произошла ошибка во время обработки вашего запроса веб-сервером.
    </p>
    <p>
        Пожалуйста, свяжитесь с нами, если вы думаете, что это ошибка сервера. Спасибо.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $formOffice yii\bootstrap\ActiveForm */
/* @var $formPhone yii\bootstrap\ActiveForm */
/* @var $modelOffice app\models\ConsultationOffice */
/* @var $modelPhone app\models\ConsultationPhone */

$this->title = 'Главная';
$listOptions = ['class' => 'form-control', 'prompt' => '- выбрать -'];

Modal::begin([
    'header' => '<h2>Консультация онлайн</h2>',
    'toggleButton' => ['label' => 'Консультация онлайн', 'class' => 'btn btn-success'],
]);

echo Html::textInput('text', '', ['class' => 'form-control']);

Modal::end();
?>
<div class="site-index">
    
    <div class="row">
    
        <div class="col-lg-6">
            
            <h1>Запись на консультацию в офис</h1>
        
            <?php $formOffice = ActiveForm::begin(['layout' => 'horizontal']); ?>
            
            <?= $formOffice->field($modelOffice, 'name')->textInput(['maxlength' => true]) ?>

            <?= $formOffice->field($modelOffice, 'city')->textInput(['maxlength' => true]) ?>

            <?= $formOffice->field($modelOffice, 'phone')->widget(\yii\widgets\MaskedInput::className(), ['mask' => '999-999-9999']) ?>
    
            <?= $formOffice->field($modelOffice, 'time')->dropDownList($modelOffice->consultation_time, $listOptions) ?>
    
            <?= $formOffice->field($modelOffice, 'day')->dropDownList($modelOffice->consultation_day, $listOptions) ?>
    
            <?= $formOffice->field($modelOffice, 'text')->textArea(['rows' => '6']) ?>
            
            <div class="form-group">
                <?= Html::submitButton('Отправить', ['class' => 'btn btn-success']) ?>
            </div>
            
            <?php ActiveForm::end(); ?>
        
        </div>
        
        <div class="col-lg-6">
            
            <h1>Запись на консультацию по телефону</h1>
        
            <?php $formPhone = ActiveForm::begin(['layout' => 'horizontal']); ?>
            
            <?= $formPhone->field($modelPhone, 'name')->textInput(['maxlength' => true]) ?>

            <?= $formPhone->field($modelPhone, 'city')->textInput(['maxlength' => true]) ?>

            <?= $formPhone->field($modelPhone, 'phone')->widget(\yii\widgets\MaskedInput::className(), ['mask' => '999-999-9999']) ?>
            
            <div class="form-group">
                <?= Html::submitButton('Отправить', ['class' => 'btn btn-success']) ?>
            </div>
            
            <?php ActiveForm::end(); ?>
        
        </div>
    
    </div>
    
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/news.php
<?php

use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $dataProvider \app\models\NewsSearch */

$this->title = 'Новости';

echo ListView::widget([
    'dataProvider' => $dataProvider,
    'layout' => "{items}\n<div class=\"clearfix\"></div>{pager}",
    'itemView' => '_news_item'
]); ?>

views/site/registration.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\modules\user\models\SignupForm */

$this->title = 'Регистрация';
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                
                <?= $form->field($model, 'username') ?>
                
                <?= $form->field($model, 'email') ?>
                
                <?= $form->field($model, 'password')->passwordInput() ?>
                
                <?= $form->field($model, 'verify_password')->passwordInput() ?>
                
                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>